### ISSUE TITLE
Illegal argument

### ISSUE THREAD

**Issue by cotejp** [DaGhostman/vscode-tree-view#61]
I installed the extension and I get this error with every file I open: "Illegal argument: character must be non-negative".

I'm on macOS using v1.22.1 of VS Code and v2.3.0 of the File Tree View extension.

**Comment by DaGhostman** [comment]
Could you provide a little bit more information on what file type the issue occurs along with probably a example snipet

**Comment by cotejp** [comment]
There's not much else to say. I install the plugin, I open a JavaScript file, I get the error. I open another file, I get the error. It doesn't matter which file. 

P.S. Because of the errors, I decided to move to another extension called Code Outline which works without issues.

**Comment by DaGhostman** [comment]
Funny thing is I've noticed this behavior not only on JS but on other languages as well, and so far it seems to be because of a change in vscode itself that triggers the document change event without having active document, hence the errors. A fix that should fix this behavior is due in a couple of minutes

I am sorry you ware disappointed and will be happy if at some point you reconsider switching back :)
