### ISSUE TITLE
about Javascript support

### ISSUE THREAD

**Issue by lidi1987227** [DaGhostman/vscode-tree-view#64]
like this styles functions cloud you please support to function ?
1,  const aaa = (ele) =>{ /...}
2,  export const aaa = (ele) =>{ /...}
3,  export const aaa =function (ele){ /...}
expect  a new tab "exports" contain which has export ahead;
thanks

**Comment by DaGhostman** [comment]
Hmm, so if I get this right, you would like to have those in the 'functions' section instead of the 'exports', correct?

**Comment by DaGhostman** [comment]
Unfortunately due to some restrictions of the JS/TS parser it is not possible to tell if a variable is a function or a primitive, so it will not be possible to send variables which hold functions to the "Functions" section. On a more general overview I am not sure if it makes sense to do so in the first place and also this is related to #38. However I will keep it in mind for when I have some more spare time to actually rewrite the JS/TS logic and switch the parser.

As for your "Exports" part of the question, in the context of JS/TS those are already addressed just not with a section, but with color coding. If you have a variable/class/interface which are not exported they will be shown in yellow, if they are - green. I've picked that approach since using a section will almost always have all definitions (if you do a 1 class = 1 file approach) and if you don't export... well you cant use said classes from the outside. So that would be a no-go for not at least

For now as a workaround, I would suggest relying on "Variables" and looking at the default value changes which I hope will be available in the next couple of minutes 😃 )
