### ISSUE TITLE
C# support

### ISSUE THREAD

**Issue by DomDomHaas** [DaGhostman/vscode-tree-view#65]
Hi there

I been looking for an overview tool for visual codes for ages. For Visual Studio there is Codemaid, which is such a nice tool for keeping the overview over bigger files!

The tree-view is very nice overview tool, however I'm missing the support for C#.
So there it is Feature request: Support for C# 😄 

All the unity developers will love you 😁

**Comment by DaGhostman** [comment]
Hey, I am glad that you like the extension and C# is on the table ever since Java support was added a few months back, however the only issue I encountered, that prevents the implementation still is the lack of (or me not being able to find one) a parser that will allow me to have the AST of the current file.

However I will give it another go and see if I can find something that will get the job done, in the mean time if you know of a C# parser written in JS, please give me a link and I'll do my best to get it implemented ASAP 😃

**Comment by DaGhostman** [comment]
Probably good news I think might bring some joy :) I am experimenting with an alternative approach and depend on the official C# extension. I am experimenting with that atm and there are some small issues that will bring some inconsistencies with the rest of the of the providers BUT the support is coming, 🤞 I make it before the next release, so if 2.5 gets out - all went well (enough)
