### ISSUE TITLE
It's not work for me

### ISSUE THREAD

**Issue by eumanito** [DaGhostman/vscode-tree-view#95]
I installed the extension, but file tree view not changes.

VS Code:
Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by DaGhostman** [comment]
Hey, I am sorry to hear, could you provide a little bit more information on what is not working and possibly a code sample that reproduces the problem. Also it would be very helpful if you specify with what language are you experiencing the issues.

**Comment by eumanito** [comment]
I just install the VS Code (English version) and after I install the File Tree View extension. Nothing happened.  
It should change the file tree view. Can you help me?

**Comment by DaGhostman** [comment]
Note that the extension defines it's own "activity" in the sidebar
![treeview-activity](https://user-images.githubusercontent.com/2286949/47995987-c5865e80-e0ff-11e8-8b8f-c76928a85784.png) and in order to get the extension activated you need to reload the currently open editor. 

Also in order to have the tree visible there you need to use a _supported_ language (and optionally enable the language since some are not enabled by default) [here](https://github.com/DaGhostman/vscode-tree-view#languages) is a list of all the supported languages, and note that you might see the list of configurations under the "Contributions" tab in VSCode itself when you open the Extension Page.

Let me know if this resolves your issue or if you need any further help

**Comment by eumanito** [comment]
I got it.

![image](https://user-images.githubusercontent.com/3042269/47997059-b7c1e080-e0e1-11e8-948d-72d947b260e7.png)

Using the File Symbol Explorer menu works! But it doesn't work using the Explorer menu. Can I enable it?

In your screenshot there are folder icones in each folder, how to enable it?
![image](https://user-images.githubusercontent.com/3042269/47997383-c2c94080-e0e2-11e8-8252-5f068f80d504.png)

**Comment by DaGhostman** [comment]
Glad that you got it working, unfortunately that was the old functionality (iirc this was the behaviour pre-1.26 version), currently it is not possible to to move the view inside the File Explorer.

Tbh I was considering making it configurable, but was having doubts because of the native view that is based on the Symbol Providers, furthermore the view is empty when the language is not supported which is somewhat frustrating, hence the decision for moving it to a separate activity. Because afaik there was a related issue about hiding the view when the file that is being edited is not supported.

**Comment by DaGhostman** [comment]
As a side note, there is a shortcut to open the treeview using `ctrl+alt+t` if that could help you speed up things

**Comment by eumanito** [comment]
ok, I got it. Thanks!
